id: opecha:P006612
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17574
  title: ས་སྐྱ་པའི་བཀའ་སྲུང་རྣམས་ལ་མཆོད་གཏོར་དང་བསྐང་གསོ་དམ་ཅན་དགྱེས་པའི་མཆོད་སྤྲིན་འདོད་དགུའི་དཔག་བསམ་བཀྲ་ཤིས་ནོར་བུའི་དགའ་འཁྱིལ།
  volume: ''
  author: ''
