id: P006612
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 12:10:20.863586
source_metadata:
  id: bdr:W1KG17574
  title: ས་སྐྱ་པའི་བཀའ་སྲུང་རྣམས་ལ་མཆོད་གཏོར་དང་བསྐང་གསོ་དམ་ཅན་དགྱེས་པའི་མཆོད་སྤྲིན་འདོད་དགུའི་དཔག་བསམ་བཀྲ་ཤིས་ནོར་བུའི་དགའ་འཁྱིལ།
  author: ''
  volumes:
    87bca14deed44d688acfe446ebaeea96:
      image_group_id: I1KG17932
      title: ''
      volume_number: 1
      total_pages: 348
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
